### ISSUE TITLE
imtoken saya tidak bisa ngirim

### ISSUE THREAD

**Issue by 4muhamadilyas** [Didericis/twitter-rumor-spreader#1]

**Comment by 4muhamadilyas** [comment]
imtoken saya tidak bisa ngirim

**Comment by marleyjustin08** [comment]
>   #@[https://github.com/Diderici
Duplicate of #s/twitter-rumor-spreader/issues/1#issue-640933096](https://github.com/Didericis/twitter-rumor-spreader/issues/1#issue-640933096)

**Comment by marleyjustin08** [comment]
#
Duplicate of #

**Comment by Didericis** [comment]
@marleyjustin08 I don't understand what the issue is here.
